spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: x-read-db
      username: root
      password: root
      authentication-database: admin

  kafka:
    bootstrap-servers: localhost:9092,localhost:9093,localhost:9094
    consumer:
      group-id: x-read-consumer
      auto-offset-reset: earliest
      enable-auto-commit: true
      keyDeserializer: io.confluent.kafka.serializers.KafkaAvroDeserializer
      valueDeserializer: io.confluent.kafka.serializers.KafkaAvroDeserializer
      properties:
        schema:
          registry:
            url: http://localhost:8081
        specific:
          avro:
            reader: false # 컨슈머가 지정한 스키마 버전 사용 여부